export default {
  // generators 生成文件时所需翻译字段
  generatorMessage: 'This page is generated by the generator',
  componentMessage: 'This component is generated by the generator',
  welcome: 'Welcome to use generator to generate your file',

  // LoginScene
  loginScene: 'Login',
  submit: 'Submit',
  placeholderEmail: 'Please enter your email',
  placeholderPassword: 'Please enter your password',
  email: 'Email',
  password: 'Password',

  // HomeScene
  homeScene: 'Home Scene',
  login: 'Go to Login!',
  zh: 'Chinese',
  en: 'English',
  add: 'Add',
  minus: 'Minus',

  // AppFooter
  footer: 'react-native-boilerplate',

  // AppHeader
  back: 'Back',
};
