export default {
  generatorMessage: 'This page is generated by the generator',
  componentMessage: 'This component is generated by the generator',
  welcome: 'Welcome to use generator to generate your file',
  submit: 'Submit',
  placeholderEmail: 'Please enter your email',
  placeholderPassword: 'Please enter your password',
  email: 'Email',
  password: 'Password',
};
